name: OSAH AI PR Review

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        required: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-review:

    runs-on: ubuntu-latest

    steps:

      #########################################################
      # Checkout the repository that triggered the workflow
      #########################################################

      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: target

      #########################################################
      # Checkout AI Review repository
      #########################################################

      - name: Checkout AI Review Repository
        uses: actions/checkout@v4
        with:
          repository: osah-azularc/osah-ai-review
          token: ${{ github.token }}
          path: ai-review

      #########################################################
      # Node
      #########################################################

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      #########################################################
      # Install AI Review dependencies
      #########################################################

      - name: Install AI Review Dependencies
        working-directory: ai-review
        run: npm install

      #########################################################
      # Run Review
      #########################################################

      - name: Run AI Review
        working-directory: ai-review
        run: npm run review
        env:
          TARGET_REPO: ../target
          GITHUB_TOKEN: ${{ github.token }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
